"""
Hybrid Solar Installation and Monitoring System — Software Simulation
=======================================================================

This is a desktop (Tkinter) simulation of the system described in the
project's Methodology section. No physical hardware exists yet — no
CT clamp, no voltage sensor, no relay, no GSM module, no RGB
indicator — so every "reading" in this program is generated by a
simple synthetic day-cycle model, not measured from a real
installation. It exists purely to demonstrate, on screen, how the
six functions in the Methodology are meant to behave and interact:

    1. Baseline status display               (Methodology 1)
    2. Load balancing / export control       (Methodology 2)
    3. Predictive generation-dip forecasting (Methodology 3)
    4. Automated dual alerting               (Methodology 4)
    5. Billing verification                  (Methodology 5)
    6. Multi-client installer dashboard      (Methodology 6)

The interface is deliberately kept in black, white and grey — no
colour is used to signal state. Status is instead shown through
shape, fill pattern and bold text labels, so the same distinctions
would still be readable on a black-and-white printout.

Run with:  python hybrid_solar_monitor_sim.py
Requires:  Python 3.9+, matplotlib (pip install matplotlib)
           Tkinter ships with most desktop Python installs; on some
           Linux distributions it must be installed separately, e.g.
           sudo apt install python3-tk
"""

import random
import math
import datetime
import tkinter as tk
from tkinter import ttk, filedialog, messagebox

import matplotlib
matplotlib.use("TkAgg")
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

FONT_FAMILY = "Times New Roman"
BG = "#ffffff"
PANEL_BG = "#f2f2f2"
FG = "#000000"
BORDER = "#000000"

TICK_MS = 600            # simulated-time step, in milliseconds of real time
CREDIT_FACTOR_DOMESTIC = 0.8   # ZESA domestic net-metering credit factor, kWh credited per kWh exported
HISTORY_LEN = 120        # how many readings are kept for the rolling chart
FORECAST_WINDOW = 6      # how many recent readings the forecast model looks at


def now_str():
    return datetime.datetime.now().strftime("%H:%M:%S")


class SolarModel:
    """Generates a synthetic day-cycle of solar output plus a fixed
    household demand, standing in for the CT clamp and voltage sensor
    readings the real device would take. Cloud dips and faults can be
    injected manually to demonstrate the forecasting and alerting
    logic on demand, rather than waiting for a randomly timed event."""

    def __init__(self):
        self.t = 0
        self.demand = 55.0          # simulated constant household load, in "units"
        self.cloud_ticks_left = 0
        self.fault = False
        self.history = []           # list of (t, solar_output)

    def inject_cloud(self, duration_ticks=14):
        self.cloud_ticks_left = duration_ticks

    def toggle_fault(self, value):
        self.fault = value

    def step(self):
        self.t += 1
        # base diurnal curve: 0 at "night", peaking at simulated midday
        cycle = max(0.0, math.sin((self.t % 200) / 200 * math.pi))
        base = cycle * 100.0
        noise = random.uniform(-3, 3)
        output = max(0.0, base + noise)

        if self.cloud_ticks_left > 0:
            output *= 0.25  # heavy attenuation during a cloud event
            self.cloud_ticks_left -= 1

        if self.fault:
            output = 0.0

        self.history.append((self.t, output))
        if len(self.history) > HISTORY_LEN:
            self.history.pop(0)
        return output


class ForecastEngine:
    """Looks at the last few readings and flags a likely dip before
    output has actually collapsed, per Methodology 3. This is a
    deliberately simple trend check, not a machine-learning model —
    it is meant to demonstrate the behaviour, not to be production
    forecasting logic."""

    def __init__(self, window=FORECAST_WINDOW):
        self.window = window

    def check(self, history):
        if len(history) < self.window:
            return False
        recent = [v for _, v in history[-self.window:]]
        # simple slope check: is generation falling steadily and fast?
        diffs = [recent[i + 1] - recent[i] for i in range(len(recent) - 1)]
        avg_slope = sum(diffs) / len(diffs)
        return avg_slope < -4.0 and recent[-1] < recent[0]


class BillingLedger:
    """Independently accumulates exported energy, per Methodology 5,
    so it can later be compared against whatever figure ZESA actually
    credits the customer — entered manually here, since no public
    ZETDC interface for that figure was found during the literature
    review."""

    def __init__(self):
        self.logged_export_units = 0.0

    def add_export(self, export_amount, dt_hours):
        if export_amount > 0:
            self.logged_export_units += export_amount * dt_hours

    def verify(self, zesa_credited_units, tolerance=0.05):
        expected_credit = self.logged_export_units * CREDIT_FACTOR_DOMESTIC
        if expected_credit == 0:
            variance_pct = 0.0
        else:
            variance_pct = abs(expected_credit - zesa_credited_units) / expected_credit
        flagged = variance_pct > tolerance
        return expected_credit, variance_pct, flagged


class InstallerDashboard:
    """Holds illustrative demo rows for other clients, so the
    multi-client dashboard in Methodology has something to show
    beyond the one live-simulated installation. These other rows are
    static/randomised demonstration data only, not live readings."""

    DEMO_NAMES = ["Sengwayo Farm", "Chegutu High School", "Riverside Butchery", "Chegutu hotel"]

    def __init__(self):
        self.rows = []
        for name in self.DEMO_NAMES:
            self.rows.append({
                "name": name,
                "status": random.choice(["SOLAR", "MIXED", "GRID"]),
                "last_alert": "-",
                "variance_pct": round(random.uniform(0, 4), 1),
            })

    def maybe_update(self):
        if random.random() < 0.06:
            row = random.choice(self.rows)
            row["status"] = random.choice(["SOLAR", "MIXED", "GRID", "FAULT"])
            if row["status"] == "FAULT":
                row["last_alert"] = now_str() + "  Fault detected"


class StatusIndicator(tk.Canvas):
    """Draws the colour-free status indicator: shape and fill pattern
    encode state rather than colour, per the black-and-white brief."""

    SIZE = 130

    def __init__(self, master):
        super().__init__(master, width=self.SIZE, height=self.SIZE, bg=BG, highlightthickness=0)
        self.state = "GRID"
        self.blink_on = True
        self.draw()

    def set_state(self, state):
        self.state = state
        self.draw()

    def blink(self):
        self.blink_on = not self.blink_on
        if self.state == "FAULT":
            self.draw()

    def draw(self):
        self.delete("all")
        s = self.SIZE
        pad = 8
        if self.state == "SOLAR":
            self.create_oval(pad, pad, s - pad, s - pad, fill="#000000", outline="#000000", width=2)
            self.create_text(s / 2, s / 2, text="SOLAR", fill="#ffffff", font=(FONT_FAMILY, 11, "bold"))
        elif self.state == "MIXED":
            self.create_oval(pad, pad, s - pad, s - pad, fill="#ffffff", outline="#000000", width=2)
            self.create_arc(pad, pad, s - pad, s - pad, start=90, extent=180, fill="#000000", outline="#000000")
            self.create_text(s / 2, s - 18, text="MIXED", fill="#000000", font=(FONT_FAMILY, 11, "bold"))
        elif self.state == "GRID":
            self.create_oval(pad, pad, s - pad, s - pad, fill="#ffffff", outline="#000000", width=4)
            self.create_text(s / 2, s / 2, text="GRID", fill="#000000", font=(FONT_FAMILY, 11, "bold"))
        else:  # FAULT
            fill = "#000000" if self.blink_on else "#ffffff"
            textcol = "#ffffff" if self.blink_on else "#000000"
            self.create_oval(pad, pad, s - pad, s - pad, fill=fill, outline="#000000", width=4)
            self.create_line(pad + 10, pad + 10, s - pad - 10, s - pad - 10, fill=textcol, width=4)
            self.create_line(s - pad - 10, pad + 10, pad + 10, s - pad - 10, fill=textcol, width=4)
            self.create_text(s / 2, s - 6, text="FAULT", fill="#000000", font=(FONT_FAMILY, 10, "bold"))


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Hybrid Solar Installation and Monitoring System — Simulation")
        self.geometry("980x680")
        self.configure(bg=BG)

        style = ttk.Style(self)
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass
        style.configure(".", background=BG, foreground=FG, font=(FONT_FAMILY, 10))
        style.configure("TNotebook", background=BG)
        style.configure("TNotebook.Tab", font=(FONT_FAMILY, 10, "bold"))
        style.configure("Treeview", font=(FONT_FAMILY, 10), background="#ffffff", fieldbackground="#ffffff")
        style.configure("Treeview.Heading", font=(FONT_FAMILY, 10, "bold"))

        self.model = SolarModel()
        self.forecast = ForecastEngine()
        self.ledger = BillingLedger()
        self.dashboard = InstallerDashboard()

        self.running = False
        self.last_export_amount = 0.0
        self.forecast_flagged = False
        self.alerts = []

        self._build_banner()
        self._build_notebook()
        self.after(TICK_MS, self._blink_loop)

    # ---------------------------------------------------------- banner
    def _build_banner(self):
        banner = tk.Frame(self, bg=PANEL_BG, highlightbackground=BORDER, highlightthickness=1)
        banner.pack(fill="x", padx=10, pady=(10, 4))
        tk.Label(banner, text="SIMULATED DATA — no physical sensors connected",
                 bg=PANEL_BG, fg=FG, font=(FONT_FAMILY, 10, "bold italic")).pack(pady=4)

    # -------------------------------------------------------- notebook
    def _build_notebook(self):
        nb = ttk.Notebook(self)
        nb.pack(fill="both", expand=True, padx=10, pady=10)

        self.tab_monitor = ttk.Frame(nb)
        self.tab_forecast = ttk.Frame(nb)
        self.tab_alerts = ttk.Frame(nb)
        self.tab_billing = ttk.Frame(nb)
        self.tab_dashboard = ttk.Frame(nb)

        nb.add(self.tab_monitor, text="Monitor")
        nb.add(self.tab_forecast, text="Forecast")
        nb.add(self.tab_alerts, text="Alerts")
        nb.add(self.tab_billing, text="Billing Verification")
        nb.add(self.tab_dashboard, text="Installer Dashboard")

        self._build_monitor_tab()
        self._build_forecast_tab()
        self._build_alerts_tab()
        self._build_billing_tab()
        self._build_dashboard_tab()

    # --------------------------------------------------------- monitor
    def _build_monitor_tab(self):
        frame = self.tab_monitor

        left = tk.Frame(frame, bg=BG)
        left.pack(side="left", fill="y", padx=10, pady=10)

        tk.Label(left, text="System Status", bg=BG, fg=FG, font=(FONT_FAMILY, 12, "bold")).pack(pady=(0, 6))
        self.indicator = StatusIndicator(left)
        self.indicator.pack()

        self.relay_label = tk.Label(left, text="EXPORT: —", bg=BG, fg=FG, font=(FONT_FAMILY, 11, "bold"))
        self.relay_label.pack(pady=(10, 0))

        self.forecast_label = tk.Label(left, text="", bg=BG, fg=FG, font=(FONT_FAMILY, 10, "italic"))
        self.forecast_label.pack(pady=(4, 0))

        readings = tk.Frame(left, highlightbackground=BORDER, highlightthickness=1, bg=BG)
        readings.pack(pady=16, fill="x")
        self.solar_val = tk.Label(readings, text="Solar output: 0.0", bg=BG, fg=FG, font=(FONT_FAMILY, 10))
        self.demand_val = tk.Label(readings, text="Household demand: 0.0", bg=BG, fg=FG, font=(FONT_FAMILY, 10))
        self.export_val = tk.Label(readings, text="Export amount: 0.0", bg=BG, fg=FG, font=(FONT_FAMILY, 10))
        for w in (self.solar_val, self.demand_val, self.export_val):
            w.pack(anchor="w", padx=8, pady=4)

        controls = tk.Frame(frame, bg=BG)
        controls.pack(side="left", fill="both", expand=True, padx=10, pady=10)

        tk.Label(controls, text="Simulation Controls", bg=BG, fg=FG, font=(FONT_FAMILY, 12, "bold")).pack(anchor="w")

        btn_row = tk.Frame(controls, bg=BG)
        btn_row.pack(anchor="w", pady=8)
        self.start_btn = ttk.Button(btn_row, text="Start", command=self.start_sim)
        self.pause_btn = ttk.Button(btn_row, text="Pause", command=self.pause_sim)
        self.step_btn = ttk.Button(btn_row, text="Step Once", command=self.step_once)
        self.reset_btn = ttk.Button(btn_row, text="Reset", command=self.reset_sim)
        for b in (self.start_btn, self.pause_btn, self.step_btn, self.reset_btn):
            b.pack(side="left", padx=4)

        event_row = tk.Frame(controls, bg=BG)
        event_row.pack(anchor="w", pady=8)
        ttk.Button(event_row, text="Trigger Cloud Dip", command=lambda: self.model.inject_cloud()).pack(side="left", padx=4)
        self.fault_var = tk.BooleanVar(value=False)
        ttk.Checkbutton(event_row, text="Force Fault", variable=self.fault_var,
                         command=lambda: self.model.toggle_fault(self.fault_var.get())).pack(side="left", padx=10)

        demand_row = tk.Frame(controls, bg=BG)
        demand_row.pack(anchor="w", pady=8, fill="x")
        tk.Label(demand_row, text="Household demand:", bg=BG, fg=FG, font=(FONT_FAMILY, 10)).pack(side="left")
        self.demand_scale = tk.Scale(demand_row, from_=10, to=100, orient="horizontal",
                                      length=260, bg=BG, fg=FG, highlightthickness=0,
                                      command=self._on_demand_change)
        self.demand_scale.set(self.model.demand)
        self.demand_scale.pack(side="left", padx=8)

        note = ("This tab mirrors Methodology: the coloured status indicator is shown here as "
                "shape and pattern instead of colour, and the export relay decision is shown as a "
                "text state rather than an LED, so the same demonstration prints legibly in black and white.")
        tk.Label(controls, text=note, bg=BG, fg=FG, font=(FONT_FAMILY, 9, "italic"),
                 wraplength=430, justify="left").pack(anchor="w", pady=(20, 0))

    def _on_demand_change(self, value):
        self.model.demand = float(value)

    # -------------------------------------------------------- forecast
    def _build_forecast_tab(self):
        frame = self.tab_forecast
        fig = Figure(figsize=(7.5, 4.4), dpi=100)
        fig.patch.set_facecolor("#ffffff")
        self.ax = fig.add_subplot(111)
        self.ax.set_facecolor("#ffffff")
        self.canvas = FigureCanvasTkAgg(fig, master=frame)
        self.canvas.get_tk_widget().pack(fill="both", expand=True, padx=10, pady=10)
        tk.Label(frame,
                 text=("Solid black line: simulated solar output. Dotted line: household demand. "
                       "A short vertical marker appears where the forecast model (Methodology 3) "
                       "flags a likely dip before output has actually fallen."),
                 bg=BG, fg=FG, font=(FONT_FAMILY, 9, "italic"), wraplength=850, justify="left").pack(pady=(0, 10))

    def _redraw_chart(self):
        self.ax.clear()
        if self.model.history:
            xs = [t for t, _ in self.model.history]
            ys = [v for _, v in self.model.history]
            self.ax.plot(xs, ys, color="#000000", linewidth=1.6, label="Solar output")
            self.ax.axhline(self.model.demand, color="#000000", linewidth=1.0, linestyle=":", label="Demand")
            if self.forecast_flagged:
                self.ax.axvline(xs[-1], color="#000000", linewidth=1.2, linestyle="--", label="Dip forecast")
        self.ax.set_xlabel("Simulated time step")
        self.ax.set_ylabel("Output level")
        self.ax.legend(loc="upper right", fontsize=8)
        self.ax.set_ylim(0, 110)
        self.canvas.draw_idle()

    # --------------------------------------------------------- alerts
    def _build_alerts_tab(self):
        frame = self.tab_alerts
        tk.Label(frame, text="Automated Alert Log (Methodology 4)", bg=BG, fg=FG,
                 font=(FONT_FAMILY, 12, "bold")).pack(anchor="w", padx=10, pady=(10, 4))
        self.alert_box = tk.Listbox(frame, font=(FONT_FAMILY, 10), bg="#ffffff", fg=FG,
                                     highlightbackground=BORDER, highlightthickness=1)
        self.alert_box.pack(fill="both", expand=True, padx=10, pady=6)
        ttk.Button(frame, text="Save Log to File...", command=self._save_log).pack(anchor="w", padx=10, pady=(0, 10))

    def _log_alert(self, text):
        entry = f"[{now_str()}]  {text}  (sent to customer and installer)"
        self.alerts.append(entry)
        self.alert_box.insert(tk.END, entry)
        self.alert_box.see(tk.END)

    def _save_log(self):
        path = filedialog.asksaveasfilename(defaultextension=".txt", filetypes=[("Text file", "*.txt")])
        if path:
            with open(path, "w") as f:
                f.write("\n".join(self.alerts))
            messagebox.showinfo("Saved", "Alert log saved.")

    # -------------------------------------------------------- billing
    def _build_billing_tab(self):
        frame = self.tab_billing
        tk.Label(frame, text="Billing Verification (Methodology 5)", bg=BG, fg=FG,
                 font=(FONT_FAMILY, 12, "bold")).pack(anchor="w", padx=10, pady=(10, 4))

        box = tk.Frame(frame, bg=BG)
        box.pack(anchor="w", padx=10, pady=10)

        tk.Label(box, text="Device-logged exported units (accumulated automatically):",
                 bg=BG, fg=FG, font=(FONT_FAMILY, 10)).grid(row=0, column=0, sticky="w", pady=4)
        self.logged_units_label = tk.Label(box, text="0.00", bg=BG, fg=FG, font=(FONT_FAMILY, 10, "bold"))
        self.logged_units_label.grid(row=0, column=1, sticky="w", padx=10)

        tk.Label(box, text="Units ZESA actually credited (enter from bill):",
                 bg=BG, fg=FG, font=(FONT_FAMILY, 10)).grid(row=1, column=0, sticky="w", pady=4)
        self.zesa_entry = tk.Entry(box, width=12, font=(FONT_FAMILY, 10))
        self.zesa_entry.insert(0, "0.0")
        self.zesa_entry.grid(row=1, column=1, sticky="w", padx=10)

        ttk.Button(box, text="Verify", command=self._verify_billing).grid(row=2, column=0, pady=10, sticky="w")

        self.billing_result = tk.Label(frame, text="", bg=BG, fg=FG, font=(FONT_FAMILY, 11, "bold"))
        self.billing_result.pack(anchor="w", padx=10, pady=6)

        tk.Label(frame,
                 text=("The device keeps its own log of exported units independently of the utility. "
                       "Because no public ZETDC interface for the credited figure was found during the "
                       "literature review, that figure is entered manually here, exactly as described "
                       "in Methodology 5."),
                 bg=BG, fg=FG, font=(FONT_FAMILY, 9, "italic"), wraplength=750, justify="left").pack(anchor="w", padx=10, pady=(10, 0))

    def _verify_billing(self):
        try:
            zesa_units = float(self.zesa_entry.get())
        except ValueError:
            messagebox.showerror("Invalid input", "Enter a numeric value for ZESA-credited units.")
            return
        expected, variance_pct, flagged = self.ledger.verify(zesa_units)
        if flagged:
            text = (f"DISCREPANCY FLAGGED — expected credit ≈ {expected:.2f} units, "
                    f"ZESA credited {zesa_units:.2f} units ({variance_pct*100:.1f}% variance)")
            self._log_alert("Billing discrepancy detected during verification")
        else:
            text = (f"MATCH WITHIN TOLERANCE — expected credit ≈ {expected:.2f} units, "
                    f"ZESA credited {zesa_units:.2f} units ({variance_pct*100:.1f}% variance)")
        self.billing_result.config(text=text)

    # ------------------------------------------------------- dashboard
    def _build_dashboard_tab(self):
        frame = self.tab_dashboard
        tk.Label(frame, text="Installer Multi-Client Dashboard (Methodology 6)", bg=BG, fg=FG,
                 font=(FONT_FAMILY, 12, "bold")).pack(anchor="w", padx=10, pady=(10, 4))
        tk.Label(frame,
                 text=("The top row is this simulation's own live client. The rows below are "
                       "illustrative demonstration data for other clients, not live readings."),
                 bg=BG, fg=FG, font=(FONT_FAMILY, 9, "italic")).pack(anchor="w", padx=10, pady=(0, 6))

        cols = ("Client", "Status", "Last Alert", "Billing Variance")
        self.tree = ttk.Treeview(frame, columns=cols, show="headings", height=8)
        for c in cols:
            self.tree.heading(c, text=c)
            self.tree.column(c, width=200, anchor="w")
        self.tree.pack(fill="both", expand=True, padx=10, pady=6)

        self.tree.insert("", "end", iid="live", values=("This installation (live)", "GRID", "-", "0.0%"))
        for i, row in enumerate(self.dashboard.rows):
            self.tree.insert("", "end", iid=f"demo{i}",
                              values=(row["name"], row["status"], row["last_alert"], f"{row['variance_pct']}%"))

    def _refresh_dashboard(self, live_status, live_alert):
        self.tree.item("live", values=("This installation (live)", live_status, live_alert, "-"))
        self.dashboard.maybe_update()
        for i, row in enumerate(self.dashboard.rows):
            self.tree.item(f"demo{i}",
                            values=(row["name"], row["status"], row["last_alert"], f"{row['variance_pct']}%"))

    # ------------------------------------------------------- simulation
    def start_sim(self):
        if not self.running:
            self.running = True
            self._schedule_tick()

    def pause_sim(self):
        self.running = False

    def step_once(self):
        self._tick()

    def reset_sim(self):
        self.running = False
        self.model = SolarModel()
        self.ledger = BillingLedger()
        self.forecast_flagged = False
        self.fault_var.set(False)
        self.demand_scale.set(55)
        self.alerts.clear()
        self.alert_box.delete(0, tk.END)
        self._redraw_chart()
        self.indicator.set_state("GRID")
        self.relay_label.config(text="EXPORT: —")
        self.forecast_label.config(text="")
        self.logged_units_label.config(text="0.00")
        self.billing_result.config(text="")

    def _schedule_tick(self):
        if self.running:
            self._tick()
            self.after(TICK_MS, self._schedule_tick)

    def _tick(self):
        solar = self.model.step()
        demand = self.model.demand
        export_amount = max(0.0, solar - demand)

        self.forecast_flagged = self.forecast.check(self.model.history)
        if self.forecast_flagged and export_amount > 0:
            export_amount *= 0.5  # pre-emptively reduce export ahead of the predicted dip
            self.forecast_label.config(text="Forecast: likely dip ahead — export reduced pre-emptively")
        else:
            self.forecast_label.config(text="")

        if self.model.fault:
            state = "FAULT"
            export_amount = 0.0
        elif export_amount > 5:
            state = "SOLAR"
        elif solar > 5:
            state = "MIXED"
        else:
            state = "GRID"

        self.indicator.set_state(state)
        self.relay_label.config(text=f"EXPORT: {'ALLOWED' if export_amount > 0 else 'BLOCKED'}")

        self.solar_val.config(text=f"Solar output: {solar:.1f}")
        self.demand_val.config(text=f"Household demand: {demand:.1f}")
        self.export_val.config(text=f"Export amount: {export_amount:.1f}")

        dt_hours = (TICK_MS / 1000.0) / 3600.0 * 50  # scaled so the demo accumulates a visible total quickly
        self.ledger.add_export(export_amount, dt_hours)
        self.logged_units_label.config(text=f"{self.ledger.logged_export_units:.2f}")

        if self.model.fault:
            if not self.alerts or "Fault" not in self.alerts[-1]:
                self._log_alert("Fault detected — generation dropped to zero unexpectedly")
        elif self.forecast_flagged and export_amount > 0:
            if not self.alerts or "dip" not in self.alerts[-1]:
                self._log_alert("Predicted generation dip — export reduced pre-emptively")

        self._redraw_chart()
        self._refresh_dashboard(state, self.alerts[-1] if self.alerts else "-")

    def _blink_loop(self):
        self.indicator.blink()
        self.after(500, self._blink_loop)


if __name__ == "__main__":
    app = App()
    app.mainloop()